Added my current OOTR discography
DaruniasJoy/OoT-Custom-Sequences pull request #349
Opened 2023-04-13 00:57 UTC by DetectiveSky

If there are any too-spicy sequences let me know, I'll remove them.

2023-04-13 21:58 UTC, DetectiveSky commented
I've put the timestamps in the commit message but now I realize i should put them here instead

LoD Sinking Old Sanctuary, 1:41, loop at 11s - Simon's Theme Fanfare is a fanfare - CotM Dance of Illusions, 0:48, loop from beginning - SotN Lost Painting, 1:42, loop from 0:15 - Dance of Death, 1:12, loop from 0:05 - Deja Vu, 0:57, loop from 4s - Going Alone, 1:04, loop from 0:09 - Zelda Ura Temple of Time, 0:54, loop from beginning

2023-04-13 22:23 UTC, PurpleHato requested changes

2023-04-13 22:23 UTC, PurpleHato commented on data/Music/Castlevania Series/Super Castlevania 4/DS612SimonsThemeFanfare.meta
> +Super Castlevania 4 - Vital Soul Get
Super Castlevania IV - Vital Soul Get

2023-04-13 22:23 UTC, PurpleHato commented on data/Music/The Legend of Zelda Series/Ura Zelda/DS612TempleOfTimeUra.meta
> +The Legend of Zelda Ura - Temple of Time
The Legend of Zelda: Ura - Temple of Time

2023-04-13 23:39 UTC, DetectiveSky commented
Should be good to go now

2023-04-17 03:25 UTC, DetectiveSky commented
Lost is 49s long and loops from the beginning

2023-04-19 17:21 UTC, DaruniasJoy commented
Okay, one small Detail stops me from adding all this.

Could you do me the Favor and Rename your Files like this :

Dance Of Illusions by DS612.meta

and Fanfares like this : 
Fanfare - Simons Theme by DS612.meta

2023-04-19 21:14 UTC, merged

2023-04-19 21:14 UTC, DaruniasJoy commented
access to the spreadsheet should be granted make sure to add the tracks pls :)